spring:
  application:
    name: learnhub-user-service
server:
  port: 8000
  servlet:
    context-path: /learn-hub/user
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    default-models-expand-depth: -1
  packagesToScan: "com.internal.learnhub.user.api.controller"

config:
  app:
    app-name: LearnHub User
    version: 1.0.0
  swagger:
    name: "Amalraj P V"
    email: "amalrajpv001@gmail.com"
    title: "LearnHub Users Service"
    description: "LearnHub user and access service"
    version: "1.0.0"
